import sys
import subprocess
import argparse

try:
    import matplotlib.pyplot as plt
    import numpy as np
except ImportError:
    subprocess.check_call([sys.executable, "-m", "pip", "install", "matplotlib", "numpy"])
    import matplotlib.pyplot as plt
    import numpy as np

try:
    import pandas as pd
except ImportError:
    subprocess.check_call([sys.executable, "-m", "pip", "install", "pandas", "openpyxl"])
    import pandas as pd

def main():
    parser = argparse.ArgumentParser(description="Plot rRNA proportions from Excel file generated by calc_rrna_proportions.py")
    parser.add_argument("excel_file", help="Path to the Excel file")
    parser.add_argument("--output", default="rRNA_mapping_histogram.png", help="Path to output PNG")
    args = parser.parse_args()

    print(f"Loading data from {args.excel_file}...")

    # Load data, conditionally handling headers if a title row was added by the user
    try:
        df_human = pd.read_excel(args.excel_file, sheet_name="Human_Matrix_rRNA")
        if 'Sample' not in df_human.columns:
            df_human = pd.read_excel(args.excel_file, sheet_name="Human_Matrix_rRNA", header=1)
        
        df_gp = pd.read_excel(args.excel_file, sheet_name="GuineaPig_Matrix_rRNA")
        if 'Sample' not in df_gp.columns:
            df_gp = pd.read_excel(args.excel_file, sheet_name="GuineaPig_Matrix_rRNA", header=1)
    except ValueError:
        print("Error: Could not find 'Human_Matrix_rRNA' and 'GuineaPig_Matrix_rRNA' sheets.")
        sys.exit(1)

    # Clean up sample names
    def clean_name(name):
        if isinstance(name, str):
            return name.replace('.sortn_human.bam', '').replace('.sortn_guineapig.bam', '')
        return str(name)

    df_human['Sample_Clean'] = df_human['Sample'].apply(clean_name)
    df_gp['Sample_Clean'] = df_gp['Sample'].apply(clean_name)

    # Extract relevant columns and clean data types
    df_h = df_human[['Sample_Clean', 'Percentage_Ribosomal']].rename(columns={'Percentage_Ribosomal': 'Human (%)'}).copy()
    df_g = df_gp[['Sample_Clean', 'Percentage_Ribosomal']].rename(columns={'Percentage_Ribosomal': 'Guinea Pig (%)'}).copy()

    df_h['Human (%)'] = pd.to_numeric(df_h['Human (%)'], errors='coerce').fillna(0)
    df_g['Guinea Pig (%)'] = pd.to_numeric(df_g['Guinea Pig (%)'], errors='coerce').fillna(0)

    # Merge using left join to preserve excel row order
    df_merged = pd.merge(df_h, df_g, on='Sample_Clean', how='left').fillna(0)

    print("Generating plot...")
    fig, ax = plt.subplots(figsize=(14, 8))
    x = np.arange(len(df_merged['Sample_Clean']))
    width = 0.35

    rects1 = ax.bar(x - width/2, df_merged['Human (%)'], width, label='Human', color='skyblue')
    rects2 = ax.bar(x + width/2, df_merged['Guinea Pig (%)'], width, label='Guinea Pig', color='lightcoral')

    # Add labels, title, and custom x-axis tick labels
    ax.set_ylabel('Reads Mapped to rRNA (%)')
    ax.set_title('Proportion of rRNA Mapping by Sample')
    ax.set_xticks(x)
    ax.set_xticklabels(df_merged['Sample_Clean'], rotation=45, ha='right')
    ax.legend()

    # Add a grid for easier reading
    ax.grid(axis='y', linestyle='--', alpha=0.7)

    fig.tight_layout()
    plt.savefig(args.output, dpi=300)
    print(f"Plot saved successfully to {args.output}")

if __name__ == '__main__':
    main()
